# Generated by Django 4.1.3 on 2022-12-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="imagen",
            field=models.ImageField(default="null", upload_to=""),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="titulo",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nombre",
            field=models.CharField(max_length=110),
        ),
    ]
